version: '3.7'
services:
  backend:
    build: backend
    ports:
      - "${BACKEND_HOST_PORT}8000"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${RUNSERVER:-uvicorn backend.app.api:app --host 0.0.0.0}
    networks:
      - backend-network
    restart: ${DOCKER_RESTART:-no}

  frontend:
    build: frontend
    ports:
      - "${FRONTEND_HOST_PORT}3000"
    volumes:
      - /app/node_modules
      - ./frontend/app:/app
    depends_on:
      - backend
    links:
      - backend:backend_api
    stdin_open: true
    tty: true
    command: ${RUNFRONTEND:-/bin/bash -c "npm i && npm start"}
    networks:
      - backend-network

networks:
  backend-network:
